# AUTO-GENERATED by generate.py — do not edit manually
# Prompt: high school student study room
import bpy
import math
import os
import sys

def parse_output():
    argv = sys.argv
    if "--" in argv:
        idx = argv.index("--")
        for i in range(idx + 1, len(argv)):
            if argv[i] == "--output" and i + 1 < len(argv):
                return argv[i + 1]
    return "render.png"

def make_mat(name, color, roughness=0.8, metallic=0.0):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = (*color, 1.0)
    bsdf.inputs["Roughness"].default_value = roughness
    bsdf.inputs["Metallic"].default_value = metallic
    return mat

def assign(obj, mat):
    obj.data.materials.clear()
    obj.data.materials.append(mat)

def add_cube(loc, scale, mat):
    bpy.ops.mesh.primitive_cube_add(location=loc)
    obj = bpy.context.active_object
    obj.scale = scale
    assign(obj, mat)
    return obj

def add_cylinder(loc, radius, depth, mat):
    bpy.ops.mesh.primitive_cylinder_add(radius=radius, depth=depth, location=loc)
    obj = bpy.context.active_object
    assign(obj, mat)
    return obj

def main():
    output_path = parse_output()

    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete()

    # Materials
    floor_mat = make_mat("Floor", (0.55, 0.4, 0.25))
    wall_mat = make_mat("Wall", (0.92, 0.88, 0.80))
    desk_mat = make_mat("Desk", (0.6, 0.4, 0.2), roughness=0.5)
    leg_mat = make_mat("Legs", (0.3, 0.2, 0.1))
    chair_mat = make_mat("Chair", (0.15, 0.35, 0.6))
    book_mat1 = make_mat("Book1", (0.8, 0.1, 0.1))
    book_mat2 = make_mat("Book2", (0.1, 0.6, 0.2))
    book_mat3 = make_mat("Book3", (0.9, 0.7, 0.1))
    lamp_mat = make_mat("Lamp", (0.8, 0.8, 0.8), metallic=0.8)
    screen_mat = make_mat("Screen", (0.05, 0.05, 0.1))
    shelf_mat = make_mat("Shelf", (0.55, 0.38, 0.18))
    poster_mat = make_mat("Poster", (0.3, 0.5, 0.9))
    backpack_mat = make_mat("Backpack", (0.2, 0.25, 0.5))

    # Floor
    add_cube((0, 0, -0.1), (4, 4, 0.1), floor_mat)
    # Back wall
    add_cube((0, 4, 1.5), (4, 0.1, 1.6), wall_mat)
    # Left wall
    add_cube((-4, 0, 1.5), (0.1, 4, 1.6), wall_mat)

    # Desk top
    add_cube((0.0, 1.5, 0.78), (1.4, 0.7, 0.05), desk_mat)
    # Desk legs
    for lx, ly in [(-1.2, 0.9), (1.2, 0.9), (-1.2, 2.1), (1.2, 2.1)]:
        add_cube((lx, ly, 0.38), (0.06, 0.06, 0.38), leg_mat)

    # Chair seat
    add_cube((0.0, 0.3, 0.45), (0.55, 0.55, 0.05), chair_mat)
    # Chair back
    add_cube((0.0, -0.2, 0.75), (0.55, 0.05, 0.35), chair_mat)
    # Chair legs
    for cx, cy in [(-0.45, 0.75), (0.45, 0.75), (-0.45, -0.15), (0.45, -0.15)]:
        add_cube((cx, cy, 0.22), (0.04, 0.04, 0.22), leg_mat)

    # Monitor base
    add_cube((0.0, 1.8, 0.84), (0.18, 0.12, 0.04), leg_mat)
    # Monitor stand
    add_cube((0.0, 1.85, 0.98), (0.04, 0.04, 0.18), leg_mat)
    # Monitor screen
    add_cube((0.0, 1.9, 1.22), (0.45, 0.04, 0.28), screen_mat)

    # Books on desk
    for i, (bm, bx) in enumerate(zip([book_mat1, book_mat2, book_mat3], [-0.9, -0.7, -0.5])):
        add_cube((bx, 1.3, 0.88), (0.08, 0.15, 0.1), bm)

    # Desk lamp
    add_cube((0.9, 1.3, 0.84), (0.06, 0.06, 0.06), lamp_mat)  # base
    add_cube((0.9, 1.3, 1.05), (0.03, 0.03, 0.2), lamp_mat)   # arm
    add_cube((0.9, 1.2, 1.22), (0.12, 0.12, 0.04), lamp_mat)  # shade

    # Wall shelf
    add_cube((-1.5, 3.85, 1.8), (0.8, 0.15, 0.04), shelf_mat)
    # Books on shelf
    for i, (bm, bx) in enumerate(zip([book_mat1, book_mat3, book_mat2], [-2.0, -1.7, -1.4])):
        add_cube((bx, 3.75, 1.95), (0.1, 0.08, 0.18), bm)

    # Poster on wall
    add_cube((-0.5, 3.88, 1.9), (0.5, 0.02, 0.4), poster_mat)

    # Backpack on floor
    add_cube((-1.8, 0.5, 0.35), (0.25, 0.15, 0.35), backpack_mat)

    # Lighting
    bpy.ops.object.light_add(type="AREA", location=(2, -1, 4))
    light = bpy.context.active_object
    light.data.energy = 800
    light.data.size = 3
    light.rotation_euler = (math.radians(45), 0, math.radians(30))

    bpy.ops.object.light_add(type="AREA", location=(-2, 3, 3.5))
    light2 = bpy.context.active_object
    light2.data.energy = 300
    light2.data.size = 2

    # Camera
    bpy.ops.object.camera_add(location=(6, -4, 5))
    cam = bpy.context.active_object
    cam.rotation_euler = (math.radians(55), 0, math.radians(50))
    bpy.context.scene.camera = cam

    # World background
    world = bpy.data.worlds["World"]
    bg = world.node_tree.nodes["Background"]
    bg.inputs["Color"].default_value = (0.85, 0.85, 0.9, 1.0)
    bg.inputs["Strength"].default_value = 0.5

    # Render settings
    scene = bpy.context.scene
    scene.render.engine = "BLENDER_EEVEE"
    scene.render.resolution_x = 800
    scene.render.resolution_y = 600
    scene.render.image_settings.file_format = "PNG"
    scene.render.filepath = os.path.abspath(output_path)

    bpy.ops.render.render(write_still=True)

main()